name: home
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  like_button: ^2.0.4
  cupertino_icons: ^1.0.2
  percent_indicator: ^3.4.0
  google_maps_flutter: ^2.1.1
  cloud_firestore : ^3.1.7
  firebase_database : ^7.1.0
  intl: ^0.17.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  google_sign_in: ^5.2.4
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
